name: h1_ai_app
description: H1-AI Assistant Pharmacy Mobile App
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:

  # Chat & API
  http: ^1.2.0
  web_socket_channel: ^3.0.0
  flutter_markdown: ^0.7.0
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  go_router: ^14.2.7
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
