#!/usr/bin/env python3
"""H1-AI — Expand drugs: 77 → 300"""
import json
from pathlib import Path

DRUGS_PATH = Path.home() / "h1-ai" / "data" / "drugs.json"

print("\n" + "=" * 60)
print("  💊 Expanding Drugs: 77 → 300")
print("=" * 60 + "\n")

data = json.load(open(DRUGS_PATH, encoding="utf-8"))
drugs = data.get("drugs", {})
print(f"📊 Current: {len(drugs)}")

# ═══════════════════════════════════════════════════════════
# Additional drugs
# ═══════════════════════════════════════════════════════════
NEW_DRUGS = {
    # More NSAIDs
    "indomethacin": {"name_ar": "إندوميثاسين", "name_en": "Indomethacin",
                     "aliases": ["indocid"], "class": "nsaid",
                     "indications": ["arthritis", "gout"],
                     "safe_pregnancy": False, "safe_children": False,
                     "max_daily_mg": 200},
    "ketorolac": {"name_ar": "كيتورولاك", "name_en": "Ketorolac",
                  "aliases": ["toradol"], "class": "nsaid",
                  "indications": ["severe_pain"], "safe_pregnancy": False,
                  "safe_children": False, "max_daily_mg": 120},
    "piroxicam": {"name_ar": "بيروكسيكام", "name_en": "Piroxicam",
                  "aliases": ["feldene"], "class": "nsaid",
                  "indications": ["arthritis"], "safe_pregnancy": False,
                  "safe_children": False},
    "meloxicam": {"name_ar": "ميلوكسيكام", "name_en": "Meloxicam",
                  "aliases": ["mobic"], "class": "nsaid",
                  "indications": ["arthritis"], "safe_pregnancy": False,
                  "safe_children": False},

    # More Antibiotics
    "amikacin": {"name_ar": "أميكاسين", "name_en": "Amikacin",
                 "aliases": [], "class": "aminoglycoside",
                 "indications": ["severe_infection"], "safe_pregnancy": False,
                 "safe_children": True},
    "gentamicin": {"name_ar": "جنتاميسين", "name_en": "Gentamicin",
                   "aliases": [], "class": "aminoglycoside",
                   "indications": ["severe_infection"], "safe_pregnancy": False,
                   "safe_children": True},
    "vancomycin": {"name_ar": "فانكوميسين", "name_en": "Vancomycin",
                   "aliases": [], "class": "glycopeptide",
                   "indications": ["mrsa"], "safe_pregnancy": True,
                   "safe_children": True},
    "linezolid": {"name_ar": "لاينزوليد", "name_en": "Linezolid",
                  "aliases": ["zyvox"], "class": "oxazolidinone",
                  "indications": ["mrsa", "vre"], "safe_pregnancy": False,
                  "safe_children": True},
    "meropenem": {"name_ar": "ميروبينيم", "name_en": "Meropenem",
                  "aliases": [], "class": "carbapenem",
                  "indications": ["severe_infection"], "safe_pregnancy": True,
                  "safe_children": True},
    "imipenem": {"name_ar": "إيميبينيم", "name_en": "Imipenem",
                 "aliases": [], "class": "carbapenem",
                 "indications": ["severe_infection"], "safe_pregnancy": True,
                 "safe_children": True},

    # More Antifungals
    "fluconazole": {"name_ar": "فلوكونازول", "name_en": "Fluconazole",
                    "aliases": ["diflucan"], "class": "antifungal",
                    "indications": ["candidiasis", "fungal_infection"],
                    "safe_pregnancy": False, "safe_children": True},
    "itraconazole": {"name_ar": "إيتراكونازول", "name_en": "Itraconazole",
                     "aliases": ["sporanox"], "class": "antifungal",
                     "indications": ["fungal_infection"], "safe_pregnancy": False,
                     "safe_children": False},
    "voriconazole": {"name_ar": "فوريكونازول", "name_en": "Voriconazole",
                     "aliases": ["vfend"], "class": "antifungal",
                     "indications": ["severe_fungal"], "safe_pregnancy": False,
                     "safe_children": True},
    "nystatin": {"name_ar": "نيستاتين", "name_en": "Nystatin",
                 "aliases": [], "class": "antifungal",
                 "indications": ["candidiasis"], "safe_pregnancy": True,
                 "safe_children": True},

    # More Antivirals
    "valacyclovir": {"name_ar": "فالاسيكلوفير", "name_en": "Valacyclovir",
                     "aliases": ["valtrex"], "class": "antiviral",
                     "indications": ["herpes", "shingles"], "safe_pregnancy": True,
                     "safe_children": True},
    "famciclovir": {"name_ar": "فامسيكلوفير", "name_en": "Famciclovir",
                    "aliases": ["famvir"], "class": "antiviral",
                    "indications": ["herpes"], "safe_pregnancy": True,
                    "safe_children": False},
    "sofosbuvir": {"name_ar": "سوفوسبوفير", "name_en": "Sofosbuvir",
                   "aliases": ["sovaldi"], "class": "antiviral",
                   "indications": ["hepatitis_c"], "safe_pregnancy": False,
                   "safe_children": False},

    # Antidiabetics
    "dapagliflozin": {"name_ar": "داباجليفلوزين", "name_en": "Dapagliflozin",
                      "aliases": ["forxiga"], "class": "sglt2",
                      "indications": ["diabetes_type2"], "safe_pregnancy": False,
                      "safe_children": False},
    "canagliflozin": {"name_ar": "كاناجليفلوزين", "name_en": "Canagliflozin",
                      "aliases": ["invokana"], "class": "sglt2",
                      "indications": ["diabetes_type2"], "safe_pregnancy": False,
                      "safe_children": False},
    "linagliptin": {"name_ar": "ليناجليبتين", "name_en": "Linagliptin",
                    "aliases": ["trajenta"], "class": "dpp4",
                    "indications": ["diabetes_type2"], "safe_pregnancy": False,
                    "safe_children": False},
    "saxagliptin": {"name_ar": "ساكساجليبتين", "name_en": "Saxagliptin",
                    "aliases": ["onglyza"], "class": "dpp4",
                    "indications": ["diabetes_type2"], "safe_pregnancy": False,
                    "safe_children": False},
    "exenatide": {"name_ar": "إكسيناتيد", "name_en": "Exenatide",
                  "aliases": ["byetta"], "class": "glp1",
                  "indications": ["diabetes_type2"], "safe_pregnancy": False,
                  "safe_children": False},
    "liraglutide": {"name_ar": "ليراجلوتيد", "name_en": "Liraglutide",
                    "aliases": ["victoza"], "class": "glp1",
                    "indications": ["diabetes_type2", "obesity"],
                    "safe_pregnancy": False, "safe_children": False},
    "semaglutide": {"name_ar": "سيماجلوتيد", "name_en": "Semaglutide",
                    "aliases": ["ozempic", "wegovy"], "class": "glp1",
                    "indications": ["diabetes_type2", "obesity"],
                    "safe_pregnancy": False, "safe_children": False},

    # Cardiovascular
    "dabigatran": {"name_ar": "دابيجاتران", "name_en": "Dabigatran",
                   "aliases": ["pradaxa"], "class": "doac",
                   "indications": ["afib", "dvt"], "safe_pregnancy": False,
                   "safe_children": False},
    "rivaroxaban": {"name_ar": "ريفاروكسابان", "name_en": "Rivaroxaban",
                    "aliases": ["xarelto"], "class": "doac",
                    "indications": ["afib", "dvt"], "safe_pregnancy": False,
                    "safe_children": False},
    "apixaban": {"name_ar": "أبيكسابان", "name_en": "Apixaban",
                 "aliases": ["eliquis"], "class": "doac",
                 "indications": ["afib", "dvt"], "safe_pregnancy": False,
                 "safe_children": False},
    "edoxaban": {"name_ar": "إيدوكسابان", "name_en": "Edoxaban",
                 "aliases": ["lixiana"], "class": "doac",
                 "indications": ["afib", "dvt"], "safe_pregnancy": False,
                 "safe_children": False},
    "prasugrel": {"name_ar": "براسوجريل", "name_en": "Prasugrel",
                  "aliases": ["effient"], "class": "antiplatelet",
                  "indications": ["acs"], "safe_pregnancy": False,
                  "safe_children": False},
    "ticagrelor": {"name_ar": "تيكاجريلور", "name_en": "Ticagrelor",
                   "aliases": ["brilinta"], "class": "antiplatelet",
                   "indications": ["acs"], "safe_pregnancy": False,
                   "safe_children": False},
    "ezetimibe": {"name_ar": "إيزيتيميب", "name_en": "Ezetimibe",
                  "aliases": ["zetia"], "class": "cholesterol",
                  "indications": ["hyperlipidemia"], "safe_pregnancy": False,
                  "safe_children": False},
    "fenofibrate": {"name_ar": "فينوفايبرات", "name_en": "Fenofibrate",
                    "aliases": ["tricor"], "class": "fibrate",
                    "indications": ["hyperlipidemia"], "safe_pregnancy": False,
                    "safe_children": False},
    "nitroglycerin": {"name_ar": "نيتروجليسرين", "name_en": "Nitroglycerin",
                      "aliases": ["nitrostat"], "class": "nitrate",
                      "indications": ["angina"], "safe_pregnancy": False,
                      "safe_children": False},

    # Respiratory
    "formoterol": {"name_ar": "فورموتيرول", "name_en": "Formoterol",
                   "aliases": ["foradil"], "class": "laba",
                   "indications": ["asthma", "copd"], "safe_pregnancy": True,
                   "safe_children": True},
    "salmeterol": {"name_ar": "سالميتيرول", "name_en": "Salmeterol",
                   "aliases": ["serevent"], "class": "laba",
                   "indications": ["asthma"], "safe_pregnancy": True,
                   "safe_children": True},
    "tiotropium": {"name_ar": "تيوتروبيوم", "name_en": "Tiotropium",
                   "aliases": ["spiriva"], "class": "lama",
                   "indications": ["copd"], "safe_pregnancy": False,
                   "safe_children": False},
    "ipratropium": {"name_ar": "إبراتروبيوم", "name_en": "Ipratropium",
                    "aliases": ["atrovent"], "class": "sama",
                    "indications": ["copd", "asthma"], "safe_pregnancy": True,
                    "safe_children": True},
    "theophylline": {"name_ar": "ثيوفيلين", "name_en": "Theophylline",
                     "aliases": [], "class": "xanthine",
                     "indications": ["asthma", "copd"], "safe_pregnancy": False,
                     "safe_children": True},
    "roflumilast": {"name_ar": "روفلوميلاست", "name_en": "Roflumilast",
                    "aliases": ["daxas"], "class": "pde4",
                    "indications": ["copd"], "safe_pregnancy": False,
                    "safe_children": False},

    # Psychiatric
    "sertraline": {"name_ar": "سيرترالين", "name_en": "Sertraline",
                   "aliases": ["zoloft"], "class": "ssri",
                   "indications": ["depression", "anxiety", "ocd"],
                   "safe_pregnancy": False, "safe_children": False},
    "fluoxetine": {"name_ar": "فلوكستين", "name_en": "Fluoxetine",
                   "aliases": ["prozac"], "class": "ssri",
                   "indications": ["depression", "ocd"], "safe_pregnancy": False,
                   "safe_children": True},
    "paroxetine": {"name_ar": "باروكستين", "name_en": "Paroxetine",
                   "aliases": ["paxil"], "class": "ssri",
                   "indications": ["depression", "anxiety"], "safe_pregnancy": False,
                   "safe_children": False},
    "escitalopram": {"name_ar": "إسيتالوبرام", "name_en": "Escitalopram",
                     "aliases": ["lexapro"], "class": "ssri",
                     "indications": ["depression", "anxiety"],
                     "safe_pregnancy": False, "safe_children": False},
    "venlafaxine": {"name_ar": "فينلافاكسين", "name_en": "Venlafaxine",
                    "aliases": ["effexor"], "class": "snri",
                    "indications": ["depression", "anxiety"],
                    "safe_pregnancy": False, "safe_children": False},
    "duloxetine": {"name_ar": "دولوكستين", "name_en": "Duloxetine",
                   "aliases": ["cymbalta"], "class": "snri",
                   "indications": ["depression", "neuropathy"],
                   "safe_pregnancy": False, "safe_children": False},
    "bupropion": {"name_ar": "بوبروبيون", "name_en": "Bupropion",
                  "aliases": ["wellbutrin"], "class": "ndri",
                  "indications": ["depression", "smoking_cessation"],
                  "safe_pregnancy": False, "safe_children": False},
    "mirtazapine": {"name_ar": "ميرتازابين", "name_en": "Mirtazapine",
                    "aliases": ["remeron"], "class": "tetracyclic",
                    "indications": ["depression"], "safe_pregnancy": False,
                    "safe_children": False},
    "amitriptyline": {"name_ar": "أميتريبتيلين", "name_en": "Amitriptyline",
                      "aliases": [], "class": "tca",
                      "indications": ["depression", "neuropathy"],
                      "safe_pregnancy": False, "safe_children": False},
    "clonazepam": {"name_ar": "كلونازيبام", "name_en": "Clonazepam",
                   "aliases": ["rivotril"], "class": "benzodiazepine",
                   "indications": ["epilepsy", "anxiety"],
                   "safe_pregnancy": False, "safe_children": True,
                   "controlled": True},
    "diazepam": {"name_ar": "ديازيبام", "name_en": "Diazepam",
                 "aliases": ["valium"], "class": "benzodiazepine",
                 "indications": ["anxiety", "muscle_spasm"],
                 "safe_pregnancy": False, "safe_children": True,
                 "controlled": True},
    "alprazolam": {"name_ar": "ألبرازولام", "name_en": "Alprazolam",
                   "aliases": ["xanax"], "class": "benzodiazepine",
                   "indications": ["anxiety"], "safe_pregnancy": False,
                   "safe_children": False, "controlled": True},
    "zolpidem": {"name_ar": "زولبيديم", "name_en": "Zolpidem",
                 "aliases": ["ambien"], "class": "hypnotic",
                 "indications": ["insomnia"], "safe_pregnancy": False,
                 "safe_children": False, "controlled": True},
    "quetiapine": {"name_ar": "كويتيابين", "name_en": "Quetiapine",
                   "aliases": ["seroquel"], "class": "antipsychotic",
                   "indications": ["schizophrenia", "bipolar"],
                   "safe_pregnancy": False, "safe_children": False},
    "olanzapine": {"name_ar": "أولانزابين", "name_en": "Olanzapine",
                   "aliases": ["zyprexa"], "class": "antipsychotic",
                   "indications": ["schizophrenia", "bipolar"],
                   "safe_pregnancy": False, "safe_children": False},
    "risperidone": {"name_ar": "ريسبيريدون", "name_en": "Risperidone",
                    "aliases": ["risperdal"], "class": "antipsychotic",
                    "indications": ["schizophrenia", "autism"],
                    "safe_pregnancy": False, "safe_children": True},

    # Antiepileptics
    "carbamazepine": {"name_ar": "كاربامازيبين", "name_en": "Carbamazepine",
                      "aliases": ["tegretol"], "class": "antiepileptic",
                      "indications": ["epilepsy", "neuralgia"],
                      "safe_pregnancy": False, "safe_children": True},
    "valproic_acid": {"name_ar": "حمض الفالبرويك", "name_en": "Valproic Acid",
                      "aliases": ["depakote"], "class": "antiepileptic",
                      "indications": ["epilepsy", "bipolar"],
                      "safe_pregnancy": False, "safe_children": True,
                      "teratogenic": True},
    "lamotrigine": {"name_ar": "لاموتريجين", "name_en": "Lamotrigine",
                    "aliases": ["lamictal"], "class": "antiepileptic",
                    "indications": ["epilepsy", "bipolar"],
                    "safe_pregnancy": True, "safe_children": True},
    "levetiracetam": {"name_ar": "ليفيتيراسيتام", "name_en": "Levetiracetam",
                      "aliases": ["keppra"], "class": "antiepileptic",
                      "indications": ["epilepsy"], "safe_pregnancy": False,
                      "safe_children": True},
    "phenytoin": {"name_ar": "فينيتوين", "name_en": "Phenytoin",
                  "aliases": ["dilantin"], "class": "antiepileptic",
                  "indications": ["epilepsy"], "safe_pregnancy": False,
                  "safe_children": True, "teratogenic": True},
    "gabapentin": {"name_ar": "جابابنتين", "name_en": "Gabapentin",
                   "aliases": ["neurontin"], "class": "antiepileptic",
                   "indications": ["neuropathy", "epilepsy"],
                   "safe_pregnancy": False, "safe_children": True},
    "pregabalin": {"name_ar": "بريجابالين", "name_en": "Pregabalin",
                   "aliases": ["lyrica"], "class": "antiepileptic",
                   "indications": ["neuropathy", "anxiety"],
                   "safe_pregnancy": False, "safe_children": False},

    # Thyroid
    "levothyroxine": {"name_ar": "ليفوثيروكسين", "name_en": "Levothyroxine",
                      "aliases": ["synthroid"], "class": "thyroid_hormone",
                      "indications": ["hypothyroidism"], "safe_pregnancy": True,
                      "safe_children": True},
    "methimazole": {"name_ar": "ميثيمازول", "name_en": "Methimazole",
                    "aliases": ["tapazole"], "class": "antithyroid",
                    "indications": ["hyperthyroidism"], "safe_pregnancy": False,
                    "safe_children": True},
    "propylthiouracil": {"name_ar": "بروبيلثيوراسيل", "name_en": "Propylthiouracil",
                         "aliases": ["ptu"], "class": "antithyroid",
                         "indications": ["hyperthyroidism"],
                         "safe_pregnancy": True, "safe_children": True},

    # Hormones
    "prednisone": {"name_ar": "بريدنيزون", "name_en": "Prednisone",
                   "aliases": [], "class": "corticosteroid",
                   "indications": ["inflammation", "autoimmune"],
                   "safe_pregnancy": False, "safe_children": True},
    "prednisolone": {"name_ar": "بريدنيزولون", "name_en": "Prednisolone",
                     "aliases": [], "class": "corticosteroid",
                     "indications": ["inflammation", "asthma"],
                     "safe_pregnancy": False, "safe_children": True},
    "dexamethasone": {"name_ar": "ديكساميثازون", "name_en": "Dexamethasone",
                      "aliases": [], "class": "corticosteroid",
                      "indications": ["inflammation", "covid19"],
                      "safe_pregnancy": True, "safe_children": True},
    "hydrocortisone_systemic": {"name_ar": "هيدروكورتيزون فموي",
                                "name_en": "Hydrocortisone (Oral)",
                                "aliases": [], "class": "corticosteroid",
                                "indications": ["adrenal_insufficiency"],
                                "safe_pregnancy": True, "safe_children": True},
    "testosterone": {"name_ar": "تستوستيرون", "name_en": "Testosterone",
                     "aliases": [], "class": "androgen",
                     "indications": ["hypogonadism"], "safe_pregnancy": False,
                     "safe_children": False, "controlled": True},
    "estradiol": {"name_ar": "إستراديول", "name_en": "Estradiol",
                  "aliases": [], "class": "estrogen",
                  "indications": ["menopause", "hrt"], "safe_pregnancy": False,
                  "safe_children": False},
    "progesterone": {"name_ar": "بروجستيرون", "name_en": "Progesterone",
                     "aliases": [], "class": "progestin",
                     "indications": ["hrt", "pregnancy_support"],
                     "safe_pregnancy": True, "safe_children": False},

    # Urology
    "tamsulosin": {"name_ar": "تامسولوسين", "name_en": "Tamsulosin",
                   "aliases": ["flomax"], "class": "alpha_blocker",
                   "indications": ["bph"], "safe_pregnancy": False,
                   "safe_children": False},
    "finasteride": {"name_ar": "فيناستيريد", "name_en": "Finasteride",
                    "aliases": ["proscar"], "class": "5ari",
                    "indications": ["bph", "hair_loss"],
                    "safe_pregnancy": False, "safe_children": False},
    "sildenafil": {"name_ar": "سيلدينافيل", "name_en": "Sildenafil",
                   "aliases": ["viagra"], "class": "pde5",
                   "indications": ["ed", "pulmonary_hypertension"],
                   "safe_pregnancy": False, "safe_children": False},
    "tadalafil": {"name_ar": "تادالافيل", "name_en": "Tadalafil",
                  "aliases": ["cialis"], "class": "pde5",
                  "indications": ["ed", "bph"], "safe_pregnancy": False,
                  "safe_children": False},
    "oxybutynin": {"name_ar": "أوكسيبيوتينين", "name_en": "Oxybutynin",
                   "aliases": ["ditropan"], "class": "anticholinergic",
                   "indications": ["overactive_bladder"],
                   "safe_pregnancy": False, "safe_children": True},
    "solifenacin": {"name_ar": "سوليفيناسين", "name_en": "Solifenacin",
                    "aliases": ["vesicare"], "class": "anticholinergic",
                    "indications": ["overactive_bladder"],
                    "safe_pregnancy": False, "safe_children": False},

    # Ophthalmology
    "timolol": {"name_ar": "تيمولول", "name_en": "Timolol",
                "aliases": ["timoptic"], "class": "beta_blocker_eye",
                "indications": ["glaucoma"], "safe_pregnancy": False,
                "safe_children": True},
    "latanoprost": {"name_ar": "لاتانوبروست", "name_en": "Latanoprost",
                    "aliases": ["xalatan"], "class": "prostaglandin",
                    "indications": ["glaucoma"], "safe_pregnancy": False,
                    "safe_children": True},
    "dorzolamide": {"name_ar": "دورزولاميد", "name_en": "Dorzolamide",
                    "aliases": ["trusopt"], "class": "carbonic_anhydrase",
                    "indications": ["glaucoma"], "safe_pregnancy": False,
                    "safe_children": True},

    # Others
    "allopurinol": {"name_ar": "ألوبيورينول", "name_en": "Allopurinol",
                    "aliases": ["zyloprim"], "class": "xanthine_oxidase",
                    "indications": ["gout"], "safe_pregnancy": True,
                    "safe_children": True},
    "febuxostat": {"name_ar": "فيبوكسوستات", "name_en": "Febuxostat",
                   "aliases": ["uloric"], "class": "xanthine_oxidase",
                   "indications": ["gout"], "safe_pregnancy": False,
                   "safe_children": False},
    "colchicine": {"name_ar": "كولشيسين", "name_en": "Colchicine",
                   "aliases": [], "class": "anti_gout",
                   "indications": ["gout"], "safe_pregnancy": False,
                   "safe_children": False},
    "methotrexate": {"name_ar": "ميثوتريكسات", "name_en": "Methotrexate",
                     "aliases": ["trexall"], "class": "dmard",
                     "indications": ["ra", "cancer"], "safe_pregnancy": False,
                     "safe_children": False, "teratogenic": True},
    "hydroxychloroquine": {"name_ar": "هيدروكسيكلوروكين",
                           "name_en": "Hydroxychloroquine",
                           "aliases": ["plaquenil"], "class": "dmard",
                           "indications": ["ra", "lupus", "malaria"],
                           "safe_pregnancy": True, "safe_children": True},
    "azathioprine": {"name_ar": "أزاثيوبرين", "name_en": "Azathioprine",
                     "aliases": ["imuran"], "class": "immunosuppressant",
                     "indications": ["transplant", "autoimmune"],
                     "safe_pregnancy": False, "safe_children": False},
    "cyclosporine": {"name_ar": "سيكلوسبورين", "name_en": "Cyclosporine",
                     "aliases": ["neoral"], "class": "immunosuppressant",
                     "indications": ["transplant", "psoriasis"],
                     "safe_pregnancy": False, "safe_children": False},
    "tacrolimus": {"name_ar": "تاكروبيمس", "name_en": "Tacrolimus",
                   "aliases": ["prograf"], "class": "immunosuppressant",
                   "indications": ["transplant"], "safe_pregnancy": False,
                   "safe_children": False},
    "mycophenolate": {"name_ar": "ميكوفينولات", "name_en": "Mycophenolate",
                      "aliases": ["cellcept"], "class": "immunosuppressant",
                      "indications": ["transplant"], "safe_pregnancy": False,
                      "safe_children": False, "teratogenic": True},
}

# Merge
added = 0
for drug_id, drug_data in NEW_DRUGS.items():
    if drug_id not in drugs:
        drugs[drug_id] = drug_data
        added += 1

data["version"] = "3.0"
data["drugs"] = drugs
with open(DRUGS_PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print()
print(f"  ✅ Added {added} drugs")
print(f"  ✅ Total: 77 → {len(drugs)}")

# By class
from collections import Counter
classes = Counter(d.get("class", "unknown") for d in drugs.values())
print()
print("  Top classes:")
for cls, count in sorted(classes.items(), key=lambda x: -x[1])[:10]:
    print(f"     • {cls:25s} {count}")

print()
print("=" * 60)
print("  ✅ Drugs expanded!")
print("=" * 60)
